theme: jekyll-theme-leap-day
title: Lazy Results
description: Jackson 3.x datatype module for Result
current_version: 0.1.0.0-SNAPSHOT
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
exclude:
  - gradle
  - result-jackson3
