[versions]
assertj = "3.27.7"
google-java-format = "1.34.1"
jackson = "3.0.4"
jacoco = "0.8.14"
japicmp = "0.4.6"
junit = "6.0.2"
nexus-publish = "2.0.0"
result-core = "1.0.2.0"
sonarqube = "7.2.2.6593"
spotless = "8.2.1"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
google-java-format = { module = "com.google.googlejavaformat:google-java-format", version.ref = "google-java-format" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
result-core = { module = "com.leakyabstractions:result", version.ref = "result-core" }

[bundles]
implementation = [ "result-core", "jackson-databind" ]
test-implementation = [ "assertj-core", "junit-jupiter-api" ]
test-runtime = [ "junit-jupiter-engine", "google-java-format" ]

[plugins]
japicmp = { id = "me.champeau.gradle.japicmp", version.ref = "japicmp" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
